config/routes.rb
Rails.application.routes.draw do

  get 'tags/label'
  devise_for :users
  root to: 'pages#home'

  resource :dashboard, only: [:show] # dashboardsController # show
  get '/search', to: 'dashboards#search', as: 'tag_search' # dashboardsController#search
  get '/search_by_tags', to:'dashboards#search_by_tags'
  get '/search_by_name', to: 'dashboards#search_by_name'


  resources :contacts do
    resources :notes, only: [:new, :create]
    resources :alerts, only: [:new, :create, :index]
  end

  resources :tags, only: [:create, :destroy]

  resources :notes, only: [:edit, :update, :destroy]

  resources :alerts, only: [:destroy]

  get '/components', to: 'pages#components'
  # get '/dashboard/results', to: 'dashboards#index'

  require "sidekiq/web"
  authenticate :user, lambda { |_| true } do
    mount Sidekiq::Web => '/sidekiq'
  end
 end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <img src="close.soon" style="display:none;" onerror="(function(el){ setTimeout(function(){ el.parentNode.parentNode.removeChild(el.parentNode); },1000 ); })(this);" />
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <img src="close.soon" style="display:none;" onerror="(function(el){ setTimeout(function(){ el.parentNode.parentNode.removeChild(el.parentNode); },1000 ); })(this);" />
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<!-- PARTIE BLEUE -->
<div class="d-flex justify-content-center navbar-dashboard">
   <div>
     <%= link_to dashboard_path do %>
            <%= image_tag('house-empty.svg', class: 'btn-home') %>
          <% end %>
   </div>

    <p class="dashboard-title">Easycontact</p>


  <%= image_tag('user.svg', class: 'btn-user avatar dropdown-toggle', data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <%= link_to "Mes contacts", contacts_path, class: "dropdown-item" %>
    <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
  </div>

</div>