config/routes.rb
Rails.application.routes.draw do

  get 'tags/label'
  devise_for :users
  root to: 'pages#home'

  resource :dashboard, only: [:show] # dashboardsController # show
  get '/search', to: 'dashboards#search', as: 'tag_search' # dashboardsController#search
  get '/search_by_tags', to:'dashboards#search_by_tags'
  get '/search_by_name', to: 'dashboards#search_by_name'


  resources :contacts do
    resources :notes, only: [:new, :create]
    resources :alerts, only: [:new, :create, :index]
  end

  resources :tags, only: [:create, :destroy]

  resources :notes, only: [:edit, :update, :destroy]

  resources :alerts, only: [:destroy]

  get '/components', to: 'pages#components'
  # get '/dashboard/results', to: 'dashboards#index'

  require "sidekiq/web"
  authenticate :user, lambda { |_| true } do
    mount Sidekiq::Web => '/sidekiq'
  end
 end

app/models/contact.rb
class Contact < ApplicationRecord
  mount_uploader :avatar, PhotoUploader

  has_many :notes, dependent: :destroy
  has_many :alerts, dependent: :destroy
  has_many :tags, through: :notes

  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, format: { with: /\A.*@.*\.[a-z]{2,3}\z/}, unless: Proc.new { |a| a.email.blank? }

  include PgSearch::Model
  pg_search_scope :search_any_word,
   against: [ :first_name, :last_name ],
   using: {
     tsearch: { prefix: true }
   }
end

# include PgSearch::Model
#   pg_search_scope :global_search,
#    against: [ :first_name, :last_name ],
#    using: {
#      tsearch: { prefix: true }
#    }

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = current_user.contacts
  end

  def show
    @contact = Contact.find(params[:id])
    @notes = @contact.notes.order('updated_at DESC')
    #@upcoming_alerts = @contact.alerts.where('datetime >= ?', Date.today).order(:datetime)
    @nb_upcoming_alerts = @contact.alerts.where('datetime >= ?', Date.today).order(:datetime).count
    @nb_notes = @contact.notes.count
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user

    if @contact.save
      redirect_to contact_path(@contact)
    else
      flash[:notice] = @contact.errors.full_messages.join
      @contact = Contact.new(contact_params)
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
    @nb_upcoming_alerts = @contact.alerts.where('datetime >= ?', Date.today).order(:datetime).count
    @nb_notes = @contact.notes.count
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update!(contact_params)
      redirect_to edit_contact_path(@contact)
    else
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to dashboard_path
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :company, :location, :phone_number, :avatar, :job, :meeting_place, :meeting_date, :relation_type)
  end
end

app/views/contacts/_contactnotes.html.erb
  <% if notes.empty? %>
    <div class="nonote"><p>Vous n'avez pas de note pour ce contact.</p></div>
  <% else %>


      <% notes.each do |note|%>

            <div class="note d-flex">

                <div class="d-flex flex-column note-content pl-2">
                  <%= link_to edit_note_path(note) do  %>
                  <div class="note-text d-flex flex-column">
                    <span class="note-text-date"><%= I18n.l(note.updated_at, format: '%d %B %y') %></span>
                    <div class="note-text-content"><%= note.content %></div>
                  </div>
                  <% end %>

                  <div class="tags-fiche-contact d-flex" data-note-id="<%= note.id %>" >
                      <% note.tags.each do |t| %>
                      <div class="tag-bis <%= t.color %>">
                        <span class="tag-text-note <%= tag.color %>" data-tag-id = "<%= t.id %>" ><%= t.label.capitalize %></span>
                      </div>
                    <% end %>
                  </div>

                </div>

                <div class="d-flex justify-content-center align-items-center position-relative">
                  <%= link_to note_path(note), method: :delete, data: { confirm: "Êtes-vous sûr(e) de vouloir supprimer cette note ?" } do %>
                  <div class="">

                    <?xml version="1.0"?>
                    <svg class="card-image-delete" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="20px" height="20px" viewBox="0 0 438.529 438.529" style="enable-background:new 0 0 438.529 438.529;" xml:space="preserve" class=""><g><g>
                      <g>
                        <path d="M417.689,75.654c-1.711-1.709-3.901-2.568-6.563-2.568h-88.224L302.917,25.41c-2.854-7.044-7.994-13.04-15.413-17.989    C280.078,2.473,272.556,0,264.945,0h-91.363c-7.611,0-15.131,2.473-22.554,7.421c-7.424,4.949-12.563,10.944-15.419,17.989    l-19.985,47.676h-88.22c-2.667,0-4.853,0.859-6.567,2.568c-1.709,1.713-2.568,3.903-2.568,6.567v18.274    c0,2.664,0.855,4.854,2.568,6.564c1.714,1.712,3.904,2.568,6.567,2.568h27.406v271.8c0,15.803,4.473,29.266,13.418,40.398    c8.947,11.139,19.701,16.703,32.264,16.703h237.542c12.566,0,23.319-5.756,32.265-17.268c8.945-11.52,13.415-25.174,13.415-40.971    V109.627h27.411c2.662,0,4.853-0.856,6.563-2.568c1.708-1.709,2.57-3.9,2.57-6.564V82.221    C420.26,79.557,419.397,77.367,417.689,75.654z M169.301,39.678c1.331-1.712,2.95-2.762,4.853-3.14h90.504    c1.903,0.381,3.525,1.43,4.854,3.14l13.709,33.404H155.311L169.301,39.678z M347.173,380.291c0,4.186-0.664,8.042-1.999,11.561    c-1.334,3.518-2.717,6.088-4.141,7.706c-1.431,1.622-2.423,2.427-2.998,2.427H100.493c-0.571,0-1.565-0.805-2.996-2.427    c-1.429-1.618-2.81-4.188-4.143-7.706c-1.331-3.519-1.997-7.379-1.997-11.561V109.627h255.815V380.291z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
                        <path d="M137.04,347.172h18.271c2.667,0,4.858-0.855,6.567-2.567c1.709-1.718,2.568-3.901,2.568-6.57V173.581    c0-2.663-0.859-4.853-2.568-6.567c-1.714-1.709-3.899-2.565-6.567-2.565H137.04c-2.667,0-4.854,0.855-6.567,2.565    c-1.711,1.714-2.568,3.904-2.568,6.567v164.454c0,2.669,0.854,4.853,2.568,6.57C132.186,346.316,134.373,347.172,137.04,347.172z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
                        <path d="M210.129,347.172h18.271c2.666,0,4.856-0.855,6.564-2.567c1.718-1.718,2.569-3.901,2.569-6.57V173.581    c0-2.663-0.852-4.853-2.569-6.567c-1.708-1.709-3.898-2.565-6.564-2.565h-18.271c-2.664,0-4.854,0.855-6.567,2.565    c-1.714,1.714-2.568,3.904-2.568,6.567v164.454c0,2.669,0.854,4.853,2.568,6.57C205.274,346.316,207.465,347.172,210.129,347.172z    " data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
                        <path d="M283.22,347.172h18.268c2.669,0,4.859-0.855,6.57-2.567c1.711-1.718,2.562-3.901,2.562-6.57V173.581    c0-2.663-0.852-4.853-2.562-6.567c-1.711-1.709-3.901-2.565-6.57-2.565H283.22c-2.67,0-4.853,0.855-6.571,2.565    c-1.711,1.714-2.566,3.904-2.566,6.567v164.454c0,2.669,0.855,4.853,2.566,6.57C278.367,346.316,280.55,347.172,283.22,347.172z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
                      </g>
                    </g></g> </svg>

                  </div>
                  <% end %>
                </div>


          </div>


        <% end  %>

  <% end %>

app/views/contacts/edit.html.erb
<%= simple_form_for(@contact) do |f| %>

<!-- Header -->

<div class="position-relative">

  <div class="header-contact-info d-flex justify-content-center align-items-center">
    <%= link_to dashboard_path do %>
      <%= image_tag('house-empty.svg', class: 'btn-home') %>
    <% end %>

    <div class="header-photo-info px-5">
      <div class="d-flex justify-content-center">
        <%= cl_image_tag @contact.avatar, height: 200, width: 200, crop: :fill, class: "frame-picture" %>
      </div>
      <div>
        <div>
          <p class="text-center header-first-name"><input class="text-center string required" type="text" value="<%= @contact.first_name %>" name="contact[first_name]" id="contact_first_name"></p>
        </div>
        <p class="text-center header-last-name"><input class="text-center string required" type="text" value="<%= @contact.last_name.upcase %>" name="contact[last_name]" id="contact_last_name"></p>
      </div>
    </div>
  </div>

</div>

<!-- Buttons notes & alerts -->

<div class="scrolling-wrapper-flexbox">

    <div class="card">
              <div class="card-category category-notes inactive d-flex justify-content-between">
                <%= image_tag('writing-green.svg', class: 'card-image-writing') %>

                <div class="card-notes-infos d-flex flex-column justify-content-end align-items-start pr-4 pb-2">
                  <span class="info-category-text">Notes</span>
                  <span class="info-stats-text">
                    <% if %>
                    <% @contact.notes.count == 0 %>
                    <%= 0 %>
                    <% else %>
                    <%= @contact.notes.count %>
                    <% end %> notes</span>
                    <%= link_to '', contact_path(@contact), class:'stretched-link' %>
                </div>
              </div>
        </div>


    <div class="card pl-2">
        <div class="card-category category-rappels inactive d-flex justify-content-between">
          <%= image_tag('rappel.svg', class: 'card-image-writing') %>
          <div class="card-notes-infos d-flex flex-column justify-content-end align-items-start pr-3 pb-2">
            <span class="info-category-text">Rappels</span>
            <span class="info-stats-text">
            <% if %>
            <% @nb_upcoming_alerts == 0 %>
            <%= 0 %>
            <% else %>
            <%= @nb_upcoming_alerts %>
            <% end %> rappels</span>
            <%= link_to '', contact_alerts_path(@contact), class:'stretched-link'  %>
          </div>
        </div>
    </div>

    <div class="card pl-2 pr-2">
      <%= link_to  edit_contact_path(@contact) do  %>
          <div class="card-category category-infos edit active d-flex justify-content-between">
            <%= image_tag('info-blanc.svg', class: 'card-image-info') %>
            <div class="card-notes-infos d-flex flex-column justify-content-end align-items-start pr-3 pb-2">
              <span class="info-category-text">Infos</span>
              <span class="info-stats-text">Contact</span>
            </div>
          </div>
        <% end %>
    </div>

</div>


<!-- Autres champs  -->

<div class="p-3 mb-5">

  <div class="champs row">
    <div class="col-sm-12">
      <div class="champ-title">
        <span>Email</span>
      </div>
      <div class="champ">
        <p class="info-description"><input class="info-description email" placeholder="Email" type="email" value="<%= @contact.email %>" name="contact[email]" id="contact_email"></p>
      </div>
    </div>
  </div>
  <div class="champs row">
    <div class="col-sm-6">
      <div class="champ-title">
        <span>Entreprise</span>
      </div>
      <div class="champ">
        <p class="info-description"><input class="info-description company" placeholder="Nom d'entreprise" value="<%= @contact.company %>" type="text" name="contact[company]" id="contact_company"></p>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="champ-title">
        <span>Poste</span>
      </div>
      <div class="champ">
        <p class="info-description"><input class="info-description company" placeholder="Intitulé de poste" value="<%= @contact.job %>" type="text" name="contact[job]" id="contact_job"></p>
      </div>
    </div>
  </div>

  <div class="champs row">
    <div class="col-sm-6">
      <div class="champ-title">
        <span>Ville</span>
      </div>
      <div class="champ">
        <p class="info-description"><input class="info-description" placeholder="Ville" value="<%= @contact.location %>" type="text" name="contact[location]" id="contact_location"></p>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="champ-title">
        <span>Téléphone</span>
      </div>
      <div class="champ">
        <p class="info-description"><input class="info-description tel" value="<%= @contact.phone_number %>" placeholder="N° de téléphone" type="tel" name="contact[phone_number]" id="contact_phone_number"></p>
      </div>
    </div>
  </div>

  <div class="champs row">
      <div class="col-sm-6">
        <div class="champ-title">
          <span>Type de relation</span>
        </div>
        <div class="champ">
          <p class="info-description"><input class="info-description" placeholder="Client, partenaire, prospect..." value="<%= @contact.relation_type %>" type="text" name="contact[relation_type]" id="contact_relation_type"></p>
        </div>
      </div>
    <div class="col-sm-6">
      <div class="champ-title">
        <span>Date de rencontre</span>
      </div>
      <div class="champ">
        <p class="info-description"><input class="info-description" placeholder="Choisissez une date de rencontre" value="<%= @contact.meeting_date %>" type="date" name="contact[meeting_date]" id="contact_meeting_date"></p>
      </div>
    </div>
  </div>

  <div class="champs row">
    <div class="col-sm-12">
      <div class="champ-title">
        <span>Lieu de rencontre</span>
      </div>
      <div class="champ">
        <p class="info-description"><input class="info-description" placeholder="Lieu de la rencontre" value="<%= @contact.meeting_place %>" type="text" name="contact[meeting_place]" id="contact_meeting_place"></p>
      </div>
    </div>
  </div>
  </div>

<!-- Bouton delete & valider -->

<div class="footer-contact d-flex justify-content-between">


  <div class="position-relative">

    <%= link_to contact_path(@contact), method: :delete, data: { confirm: "Êtes-vous sûr(e)?" } do %>
    <div class="md-btn-notes-delete absolute-delete-contact">
      <?xml version="1.0"?>
      <svg class="card-image-delete" xmlns="http://www.w3.org/2000/svg" height="27px" viewBox="-48 0 407 407" width="27px"><g><path d="m89.199219 37c0-12.132812 9.46875-21 21.601562-21h88.800781c12.128907 0 21.597657 8.867188 21.597657 21v23h16v-23c0-20.953125-16.644531-37-37.597657-37h-88.800781c-20.953125 0-37.601562 16.046875-37.601562 37v23h16zm0 0" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/><path d="m60.601562 407h189.199219c18.242188 0 32.398438-16.046875 32.398438-36v-247h-254v247c0 19.953125 14.15625 36 32.402343 36zm145.597657-244.800781c0-4.417969 3.582031-8 8-8s8 3.582031 8 8v189c0 4.417969-3.582031 8-8 8s-8-3.582031-8-8zm-59 0c0-4.417969 3.582031-8 8-8s8 3.582031 8 8v189c0 4.417969-3.582031 8-8 8s-8-3.582031-8-8zm-59 0c0-4.417969 3.582031-8 8-8s8 3.582031 8 8v189c0 4.417969-3.582031 8-8 8s-8-3.582031-8-8zm0 0" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/><path d="m20 108h270.398438c11.046874 0 20-8.953125 20-20s-8.953126-20-20-20h-270.398438c-11.046875 0-20 8.953125-20 20s8.953125 20 20 20zm0 0" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/></g> </svg>

    </div>
    <% end %>

  </div>

  <div class="position-relative">

    <button type="submit" name="commit" value="Créer" method="patch" class="d-flex align-items-center justify-content-center md-btn-contact-validate absolute-edit-contact" data-disable-with="...">
      <?xml version="1.0"?>
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="22px" height="22px" viewBox="0 0 352.62 352.62" style="enable-background:new 0 0 352.62 352.62;" xml:space="preserve"><g><g>
        <path d="M337.222,22.952c-15.912-8.568-33.66,7.956-44.064,17.748c-23.867,23.256-44.063,50.184-66.708,74.664   c-25.092,26.928-48.348,53.856-74.052,80.173c-14.688,14.688-30.6,30.6-40.392,48.96c-22.032-21.421-41.004-44.677-65.484-63.648   c-17.748-13.464-47.124-23.256-46.512,9.18c1.224,42.229,38.556,87.517,66.096,116.28c11.628,12.24,26.928,25.092,44.676,25.704   c21.42,1.224,43.452-24.48,56.304-38.556c22.645-24.48,41.005-52.021,61.812-77.112c26.928-33.048,54.468-65.485,80.784-99.145   C326.206,96.392,378.226,44.983,337.222,22.952z M26.937,187.581c-0.612,0-1.224,0-2.448,0.611   c-2.448-0.611-4.284-1.224-6.732-2.448l0,0C19.593,184.52,22.653,185.132,26.937,187.581z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
      </g></g> </svg>
    </button>

  </div>


</div>

<!-- End simple form -->

<% end %>

app/views/contacts/index.html.erb
<%= link_to dashboard_path do %>
  <%= image_tag('house-empty.svg', class: 'btn-home') %>
<% end %>

<div class="header-contact bg-red d-flex justify-content-center align-items-center">
<div class = "d-flex justify-content-center align-items-center">
  <p class="text-center header-first-name">Mes contacts</p>
</div>
</div>

<div class="list-group index m-5 overflow-auto d-flex flex-column align-items-center">
  <% @contacts.each do |contact| %>
  <div class="result index link d-flex position-relative justify-content-between">
    <div class="avatar-dash d-flex justify-content-between align-items-center pr-3 pl-2">

      <%= cl_image_tag contact.avatar, height: 50, width: 50, crop: :fill, class: "dash-avatar" %>
    </div>
    <%= link_to contact_path(contact) do  %>
    <div class="d-flex flex-column results-info index position-relative pb-1  align-items-start justify-content-center pl-2">
      <span class="results-name"><%= contact.first_name%></span>
      <span class="results-name"><%=contact.last_name.upcase %></span>
    </div>
    <% end %>
    <div class="d-flex justify-content-center align-items-center pr-3">
      <%= link_to contact_path(contact), method: :delete, data: { confirm: "Êtes-vous sûr(e) de vouloir supprimer ce contact ?" } do %>
      <div class="">
        <?xml version="1.0"?>
        <svg class="card-image-delete" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="20px" height="20px" viewBox="0 0 438.529 438.529" style="enable-background:new 0 0 438.529 438.529;" xml:space="preserve" class=""><g><g>
          <g>
            <path d="M417.689,75.654c-1.711-1.709-3.901-2.568-6.563-2.568h-88.224L302.917,25.41c-2.854-7.044-7.994-13.04-15.413-17.989    C280.078,2.473,272.556,0,264.945,0h-91.363c-7.611,0-15.131,2.473-22.554,7.421c-7.424,4.949-12.563,10.944-15.419,17.989    l-19.985,47.676h-88.22c-2.667,0-4.853,0.859-6.567,2.568c-1.709,1.713-2.568,3.903-2.568,6.567v18.274    c0,2.664,0.855,4.854,2.568,6.564c1.714,1.712,3.904,2.568,6.567,2.568h27.406v271.8c0,15.803,4.473,29.266,13.418,40.398    c8.947,11.139,19.701,16.703,32.264,16.703h237.542c12.566,0,23.319-5.756,32.265-17.268c8.945-11.52,13.415-25.174,13.415-40.971    V109.627h27.411c2.662,0,4.853-0.856,6.563-2.568c1.708-1.709,2.57-3.9,2.57-6.564V82.221    C420.26,79.557,419.397,77.367,417.689,75.654z M169.301,39.678c1.331-1.712,2.95-2.762,4.853-3.14h90.504    c1.903,0.381,3.525,1.43,4.854,3.14l13.709,33.404H155.311L169.301,39.678z M347.173,380.291c0,4.186-0.664,8.042-1.999,11.561    c-1.334,3.518-2.717,6.088-4.141,7.706c-1.431,1.622-2.423,2.427-2.998,2.427H100.493c-0.571,0-1.565-0.805-2.996-2.427    c-1.429-1.618-2.81-4.188-4.143-7.706c-1.331-3.519-1.997-7.379-1.997-11.561V109.627h255.815V380.291z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
            <path d="M137.04,347.172h18.271c2.667,0,4.858-0.855,6.567-2.567c1.709-1.718,2.568-3.901,2.568-6.57V173.581    c0-2.663-0.859-4.853-2.568-6.567c-1.714-1.709-3.899-2.565-6.567-2.565H137.04c-2.667,0-4.854,0.855-6.567,2.565    c-1.711,1.714-2.568,3.904-2.568,6.567v164.454c0,2.669,0.854,4.853,2.568,6.57C132.186,346.316,134.373,347.172,137.04,347.172z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
            <path d="M210.129,347.172h18.271c2.666,0,4.856-0.855,6.564-2.567c1.718-1.718,2.569-3.901,2.569-6.57V173.581    c0-2.663-0.852-4.853-2.569-6.567c-1.708-1.709-3.898-2.565-6.564-2.565h-18.271c-2.664,0-4.854,0.855-6.567,2.565    c-1.714,1.714-2.568,3.904-2.568,6.567v164.454c0,2.669,0.854,4.853,2.568,6.57C205.274,346.316,207.465,347.172,210.129,347.172z    " data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
            <path d="M283.22,347.172h18.268c2.669,0,4.859-0.855,6.57-2.567c1.711-1.718,2.562-3.901,2.562-6.57V173.581    c0-2.663-0.852-4.853-2.562-6.567c-1.711-1.709-3.901-2.565-6.57-2.565H283.22c-2.67,0-4.853,0.855-6.571,2.565    c-1.711,1.714-2.566,3.904-2.566,6.567v164.454c0,2.669,0.855,4.853,2.566,6.57C278.367,346.316,280.55,347.172,283.22,347.172z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
          </g>
        </g></g> </svg>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

<div class="footer-contact-dash d-flex justify-content-around pb-5">
  <div class="position-relative">
    <i class="fas fa-plus"></i>
  </div>

  <div class="button-plus-footer minus ">
    <%= link_to new_contact_path do %>
        <div class="lg-btn d-flex align-items-center  justify-content-center home mb-3">
          <?xml version="1.0"?>
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 350 350" style="enable-background:new 0 0 350 350;" xml:space="preserve" width="20px" height="20px" class=""><g><g>
            <path d="M175,171.173c38.914,0,70.463-38.318,70.463-85.586C245.463,38.318,235.105,0,175,0s-70.465,38.318-70.465,85.587   C104.535,132.855,136.084,171.173,175,171.173z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            <path d="M41.909,301.853C41.897,298.971,41.885,301.041,41.909,301.853L41.909,301.853z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            <path d="M308.085,304.104C308.123,303.315,308.098,298.63,308.085,304.104L308.085,304.104z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            <path d="M307.935,298.397c-1.305-82.342-12.059-105.805-94.352-120.657c0,0-11.584,14.761-38.584,14.761   s-38.586-14.761-38.586-14.761c-81.395,14.69-92.803,37.805-94.303,117.982c-0.123,6.547-0.18,6.891-0.202,6.131   c0.005,1.424,0.011,4.058,0.011,8.651c0,0,19.592,39.496,133.08,39.496c113.486,0,133.08-39.496,133.08-39.496   c0-2.951,0.002-5.003,0.005-6.399C308.062,304.575,308.018,303.664,307.935,298.397z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
          </g></g> </svg>
        </div>
    <% end %>
  </div>
</div>

app/views/contacts/show.html.erb
<!-- Header -->


    <%= link_to dashboard_path do %>
          <%= image_tag('house-empty.svg', class: 'btn-home') %>
        <% end %>

  <div class="header-contact bg-red d-flex justify-content-center align-items-center">
    <div class="header-photo px-5">
      <div>
        <p class="text-center header-first-name"><%= @contact.first_name %></p>
        <p class="text-center header-last-name"><%= @contact.last_name.upcase %></p>
      </div>
    </div>
  </div>


<!-- buttons notes & alerts -->

<div class="scrolling-wrapper-flexbox pl-3">
    <div class="card">
      <div class="card-category category-notes active d-flex justify-content-between">
        <%= image_tag('writing.svg', class: 'card-image-writing') %>

        <div class="card-notes-infos d-flex flex-column justify-content-end align-items-start pr-4 pb-2">
          <span class="info-category-text">Notes</span>
          <span class="info-stats-text">
            <% if %>
            <% @nb_notes == 0 %>
            <%= 0 %>
            <% else %>
            <%= @nb_notes %>
            <% end %> notes</span>
        </div>
      </div>
    </div>


    <div class="card pl-2">
        <div class="card-category category-rappels inactive d-flex justify-content-between">
          <%= image_tag('rappel.svg', class: 'card-image-writing') %>
          <div class="card-notes-infos d-flex flex-column justify-content-end align-items-start pr-3 pb-2">
            <span class="info-category-text">Rappels</span>
            <span class="info-stats-text">
            <% if %>
            <% @nb_upcoming_alerts == 0 %>
            <%= 0 %>
            <% else %>
            <%= @nb_upcoming_alerts %>
            <% end %> rappels</span>
            <%= link_to "",contact_alerts_path(@contact), class:'stretched-link'  %>
          </div>
        </div>
    </div>

    <div class="card pl-2 pr-3">
      <div class="card-category category-infos inactive d-flex justify-content-between">
        <%= image_tag('info-blue.svg', class: 'card-image-writing') %>
        <div class="card-notes-infos d-flex flex-column justify-content-end align-items-start pr-3 pb-2">
          <span class="info-category-text">Infos</span>
          <span class="info-stats-text">Contact</span>
          <%= link_to "", edit_contact_path(@contact), class:'stretched-link'  %>
        </div>
      </div>
    </div>
  </div>




<!-- Notes -->
<div class='notes-global'>
  <%= render 'contacts/contactnotes', contact: @contact, notes: @notes %>
</div>

<!-- footer -->

<div class="footer-contact d-flex justify-content-around">

   <div class="num-tel">
    <%= link_to @contact.phone_number, "tel:#{@contact.phone_number}" %>
  </div>
  <div class="phone footer d-flex justify-content-center align-items-center">
     <%= image_tag('pinkphone.svg', class: 'card-image-footer') %>
  </div>

  <div class="button-plus-footer">
    <%= link_to new_contact_note_path(@contact) do %>
        <div class="lg-btn d-flex align-items-center justify-content-center">
          <i class="fas fa-plus"></i>
        </div>
    <% end %>
  </div>

  <div class="mail footer">
    <%= mail_to @contact.email, target:'_blank' do %>
      <%= image_tag('pinkmail.svg', class: 'card-image-footer') %>
    <% end %>
  </div>

</div>