config/routes.rb
Rails.application.routes.draw do

  get 'tags/label'
  devise_for :users
  root to: 'pages#home'

  resource :dashboard, only: [:show] # dashboardsController # show
  get '/search', to: 'dashboards#search', as: 'tag_search' # dashboardsController#search
  get '/search_by_tags', to:'dashboards#search_by_tags'
  get '/search_by_name', to: 'dashboards#search_by_name'


  resources :contacts do
    resources :notes, only: [:new, :create]
    resources :alerts, only: [:new, :create, :index]
  end

  resources :tags, only: [:create, :destroy]

  resources :notes, only: [:edit, :update, :destroy]

  resources :alerts, only: [:destroy]

  get '/components', to: 'pages#components'
  # get '/dashboard/results', to: 'dashboards#index'

  require "sidekiq/web"
  authenticate :user, lambda { |_| true } do
    mount Sidekiq::Web => '/sidekiq'
  end
 end

app/models/alert.rb
class Alert < ApplicationRecord

  belongs_to :contact

  validates :title, presence: true, length: { in: 1..50 }
  validates :datetime, presence: true

end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_contact, only: [:new, :create, :index]
  before_action :set_alerts, only: [:new, :create, :index]

  def index
    @all_alerts = @contact.alerts.order(:datetime)
  end

  def new
    @alert = Alert.new
  end

  def create
    @alert = Alert.new(alert_params)
    @alert.contact = @contact

    if @alert.save
      redirect_to contact_alerts_path(@contact)
    else
      flash[:notice] = @alert.errors.full_messages.join
      render :new
      @alert = Alert.new(alert_params)
    end
  end

  def destroy
    @alert = Alert.find(params[:id])
    @alert.destroy
    redirect_to contact_alerts_path(@alert.contact)
  end

  private

  def set_alerts
    @upcoming_alerts = @contact.alerts.where('datetime >= ?', Date.today).order(:datetime)
  end

  def set_contact
    @contact = current_user.contacts.find(params[:contact_id])
  end

  def alert_params
    params.require(:alert).permit(:title, :datetime)
  end
end

app/views/alerts/index.html.erb
<!-- Header -->

<%= link_to dashboard_path do %>
          <%= image_tag('house-empty.svg', class: 'btn-home') %>
        <% end %>

  <div class="header-contact bg-red d-flex justify-content-center align-items-center">
    <div class="header-photo px-5">
      <div>
        <p class="text-center header-first-name"><%= @contact.first_name %></p>
        <p class="text-center header-last-name"><%= @contact.last_name.upcase %></p>
      </div>
    </div>
  </div>

<!-- buttons notes & alerts -->

<div class="scrolling-wrapper-flexbox pl-3">
    <div class="card">
          <div class="card-category category-notes inactive d-flex justify-content-between">
            <%= image_tag('writing-green.svg', class: 'card-image-writing') %>

            <div class="card-notes-infos d-flex flex-column justify-content-end align-items-start pr-4 pb-2">
              <span class="info-category-text">Notes</span>
              <span class="info-stats-text">
                <% if %>
                <% @contact.notes.count == 0 %>
                <%= 0 %>
                <% else %>
                <%= @contact.notes.count %>
                <% end %> notes</span>
                <%= link_to '', contact_path(@contact), class:'stretched-link'%>
            </div>
          </div>
    </div>


    <div class="card pl-2">
      <div class="card-category category-rappels active d-flex justify-content-between">
        <%= image_tag('rappel-blanc.svg', class: 'card-image-writing') %>

        <div class="card-notes-infos d-flex flex-column justify-content-end align-items-start pr-3 pb-2">
          <span class="info-category-text">Rappels</span>
          <span class="info-stats-text">
            <% if %>
            <% @upcoming_alerts.count == 0 %>
            <%= 0 %>
            <% else %>
            <%= @upcoming_alerts.count %>
            <% end %> rappels</span>
        </div>
      </div>
    </div>


    <div class="card pl-2 pr-3">
      <div class="card-category category-infos inactive d-flex justify-content-between">
        <%= image_tag('info-blue.svg', class: 'card-image-writing') %>
        <div class="card-notes-infos d-flex flex-column justify-content-end align-items-start pr-3 pb-2">
          <span class="info-category-text">Infos</span>
          <span class="info-stats-text">Contact</span>
          <%= link_to '', edit_contact_path(@contact), class:'stretched-link'  %>
        </div>
      </div>
    </div>
</div>




<!-- alerts -->


  <div class="upcoming-alerts mb-5">
    <div class="scrollable">
      <%  if @upcoming_alerts.any? %>
        <% @upcoming_alerts.each do |alert| %>
          <div class="rappels alerts d-flex align-items-center justify-content-center position-relative">

            <div class="rappels-text d-flex">
              <div>
                <span class="rappels-text-date d-flex align-items-center justify-content-center"><%= I18n.l(alert.datetime, format: "%e") %><br><%= I18n.l(alert.datetime, format: "%B") %></span>
              </div>

              <div class="rappels-text-content-alert">
                <span class="rappels-text-content d-flex align-items-center"><%= alert.title.capitalize %></span>
              </div>
            </div>

              <%= link_to alert_path(alert), method: :delete, data: { confirm: "Êtes-vous sûr(e)?" } do %>
                <div class="d-flex align-items-center justify-content-center trash-alert">
                  <?xml version="1.0"?>
                  <svg class="" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="20px" height="20px" viewBox="0 0 438.529 438.529" style="enable-background:new 0 0 438.529 438.529;" xml:space="preserve" class=""><g><g>
                    <g>
                      <path d="M417.689,75.654c-1.711-1.709-3.901-2.568-6.563-2.568h-88.224L302.917,25.41c-2.854-7.044-7.994-13.04-15.413-17.989    C280.078,2.473,272.556,0,264.945,0h-91.363c-7.611,0-15.131,2.473-22.554,7.421c-7.424,4.949-12.563,10.944-15.419,17.989    l-19.985,47.676h-88.22c-2.667,0-4.853,0.859-6.567,2.568c-1.709,1.713-2.568,3.903-2.568,6.567v18.274    c0,2.664,0.855,4.854,2.568,6.564c1.714,1.712,3.904,2.568,6.567,2.568h27.406v271.8c0,15.803,4.473,29.266,13.418,40.398    c8.947,11.139,19.701,16.703,32.264,16.703h237.542c12.566,0,23.319-5.756,32.265-17.268c8.945-11.52,13.415-25.174,13.415-40.971    V109.627h27.411c2.662,0,4.853-0.856,6.563-2.568c1.708-1.709,2.57-3.9,2.57-6.564V82.221    C420.26,79.557,419.397,77.367,417.689,75.654z M169.301,39.678c1.331-1.712,2.95-2.762,4.853-3.14h90.504    c1.903,0.381,3.525,1.43,4.854,3.14l13.709,33.404H155.311L169.301,39.678z M347.173,380.291c0,4.186-0.664,8.042-1.999,11.561    c-1.334,3.518-2.717,6.088-4.141,7.706c-1.431,1.622-2.423,2.427-2.998,2.427H100.493c-0.571,0-1.565-0.805-2.996-2.427    c-1.429-1.618-2.81-4.188-4.143-7.706c-1.331-3.519-1.997-7.379-1.997-11.561V109.627h255.815V380.291z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
                      <path d="M137.04,347.172h18.271c2.667,0,4.858-0.855,6.567-2.567c1.709-1.718,2.568-3.901,2.568-6.57V173.581    c0-2.663-0.859-4.853-2.568-6.567c-1.714-1.709-3.899-2.565-6.567-2.565H137.04c-2.667,0-4.854,0.855-6.567,2.565    c-1.711,1.714-2.568,3.904-2.568,6.567v164.454c0,2.669,0.854,4.853,2.568,6.57C132.186,346.316,134.373,347.172,137.04,347.172z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
                      <path d="M210.129,347.172h18.271c2.666,0,4.856-0.855,6.564-2.567c1.718-1.718,2.569-3.901,2.569-6.57V173.581    c0-2.663-0.852-4.853-2.569-6.567c-1.708-1.709-3.898-2.565-6.564-2.565h-18.271c-2.664,0-4.854,0.855-6.567,2.565    c-1.714,1.714-2.568,3.904-2.568,6.567v164.454c0,2.669,0.854,4.853,2.568,6.57C205.274,346.316,207.465,347.172,210.129,347.172z    " data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
                      <path d="M283.22,347.172h18.268c2.669,0,4.859-0.855,6.57-2.567c1.711-1.718,2.562-3.901,2.562-6.57V173.581    c0-2.663-0.852-4.853-2.562-6.567c-1.711-1.709-3.901-2.565-6.57-2.565H283.22c-2.67,0-4.853,0.855-6.571,2.565    c-1.711,1.714-2.566,3.904-2.566,6.567v164.454c0,2.669,0.855,4.853,2.566,6.57C278.367,346.316,280.55,347.172,283.22,347.172z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FF4D4D"/>
                    </g>
                    </g></g>
                  </svg>
                </div>
              <% end %>
          </div>
        <% end %>
      <% else %>
        <div class="nonote"><p>Vous n'avez pas de note pour ce contact.</p></div>
      <% end %>
    </div>
  </div>


<!-- footer -->

<div class="footer-contact d-flex justify-content-around">
  <div class="num-tel">
    <%= link_to @contact.phone_number, "tel:#{@contact.phone_number}" %>
  </div>
  <div class="phone footer d-flex justify-content-center align-items-center">
     <%= image_tag('pinkphone.svg', class: 'card-image-footer') %>
  </div>

  <div class="button-plus-footer">
    <%= link_to new_contact_alert_path(@contact) do %>
        <div class="lg-btn d-flex align-items-center justify-content-center">
          <i class="fas fa-plus"></i>
        </div>
    <% end %>
  </div>

  <div class="mail footer">
    <%= mail_to @contact.email do %>
      <%= image_tag('pinkmail.svg', class: 'card-image-footer') %>
    <% end %>
  </div>

</div>

app/views/alerts/new.html.erb
  <!-- NEW RAPPEL - FORM -->

  <div class="new-rappel pt-3">

    <%= simple_form_for [@contact, @alert] do |f| %>

      <div class="">
        <div>
          <div class="new-rappel-champ">
            <p class="new-rappel"><input class="string required" placeholder="Quel est le titre de votre rappel ?" type="text" name="alert[title]" id="alert_title"></p>
          </div>
      </div>

      <div class="new-rappel-champ">
          <p class="new-rappel"><%= f.input :datetime, as: :hidden, required: false, input_html: {class: "datepicker"}, label: false, placeholder:"Choisissez une date" %></p>
        </div>
      </div>

      <!-- footer -->

      <div class="footer-new-notes d-flex flex-column justify-content-center">

        <div class="text-center pt-2">
          <span class="text-footer-add-notes">Ajouter ce rappel à </span>
          <div class="d-flex justify-content-center">
            <span class="text-footer-add-notes pr-1"><%= @contact.first_name %></span>
            <span class="text-footer-add-notes"><%= @contact.last_name.capitalize %> ?</span>
          </div>
        </div>

        <div class="buttons-add-cancel">
          <div class="cancel-add-notes">
            <%= link_to contact_alerts_path(@contact) do %>
            <p class="cancel-add-notes-text">Annuler</p>
            <% end %>
          </div>
          <button type="submit" name="commit" value="Créer" method="patch" class="d-flex align-items-center justify-content-center md-btn-contact-validate validate-note-add" data-disable-with="...">
            <?xml version="1.0"?>
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" width="22px" height="22px" viewBox="0 0 352.62 352.62" style="enable-background:new 0 0 352.62 352.62;" xml:space="preserve"><g><g>
              <path d="M337.222,22.952c-15.912-8.568-33.66,7.956-44.064,17.748c-23.867,23.256-44.063,50.184-66.708,74.664   c-25.092,26.928-48.348,53.856-74.052,80.173c-14.688,14.688-30.6,30.6-40.392,48.96c-22.032-21.421-41.004-44.677-65.484-63.648   c-17.748-13.464-47.124-23.256-46.512,9.18c1.224,42.229,38.556,87.517,66.096,116.28c11.628,12.24,26.928,25.092,44.676,25.704   c21.42,1.224,43.452-24.48,56.304-38.556c22.645-24.48,41.005-52.021,61.812-77.112c26.928-33.048,54.468-65.485,80.784-99.145   C326.206,96.392,378.226,44.983,337.222,22.952z M26.937,187.581c-0.612,0-1.224,0-2.448,0.611   c-2.448-0.611-4.284-1.224-6.732-2.448l0,0C19.593,184.52,22.653,185.132,26.937,187.581z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            </g></g> </svg>
          </button>
        </div>
      </div>


      <% end %>
    </div>