config/routes.rb
Rails.application.routes.draw do

  get 'tags/label'
  devise_for :users
  root to: 'pages#home'

  resource :dashboard, only: [:show] # dashboardsController # show
  get '/search', to: 'dashboards#search', as: 'tag_search' # dashboardsController#search
  get '/search_by_tags', to:'dashboards#search_by_tags'
  get '/search_by_name', to: 'dashboards#search_by_name'


  resources :contacts do
    resources :notes, only: [:new, :create]
    resources :alerts, only: [:new, :create, :index]
  end

  resources :tags, only: [:create, :destroy]

  resources :notes, only: [:edit, :update, :destroy]

  resources :alerts, only: [:destroy]

  get '/components', to: 'pages#components'
  # get '/dashboard/results', to: 'dashboards#index'

  require "sidekiq/web"
  authenticate :user, lambda { |_| true } do
    mount Sidekiq::Web => '/sidekiq'
  end
 end

app/models/note.rb
class Note < ApplicationRecord

  belongs_to :contact

  has_many :note_tags, dependent: :destroy
  has_many :tags, through: :note_tags

  accepts_nested_attributes_for :tags
  validates :content, presence: true

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_alerts_dashboard, only: [:show]
  before_action :set_tags_dashboard, only: [:search]

  def search # set_tags_dashboard
  end

  def search_by_tags
    if params.dig(:search, :tag_ids).present?
      @notes      = Note.joins(:tags).where(tags: { id: params[:search][:tag_ids] }).distinct
      @contacts   = Contact.joins(:tags).where(tags: { id: params[:search][:tag_ids] })
      @tag_labels = Tag.where(id: params[:search][:tag_ids]).pluck(:label)
    end
    respond_to do |format|
      format.js
    end
  end

  def show
  end

  def search_by_name
    if params[:query].present?
      @contacts = Contact.search_any_word("%#{params[:query]}%").where(user: current_user)
    else
      @contacts = Contact.all.order(:last_name).where(user: current_user)
    end
    respond_to do |format|
      format.js
    end
  end


    # rails c : Contact.find_by(first_name: 'Marc').notes.first.tags


  private

  def set_alerts_dashboard
    @contacts_alerts = current_user.alerts
    @upcoming_contacts_alerts = @contacts_alerts.where('datetime >= ?', Date.today).order(:datetime)
  end

  def set_tags_dashboard
    @tags = current_user.tags
  end

  def tags_params
    params.require(:tags).permit(:label, :content, note_ids: [])
  end
end

app/views/dashboards/_searchcontacts.html.erb
 <div class="rappels-dashboard d-flex justify-content-center">
      <% if contacts.any?%>
    <div class="results pb-2">
         <div class="rappel-title">
      <span class="rappel-title">Résultats</span>
    </div>
      <% contacts.each do |contact| %>
      <div class="result d-flex justify-content-center position-relative">
        <!-- Avatar -->
          <div class="avatar-dash d-flex justify-content-center align-items-center pr-3">
            <%= cl_image_tag contact.avatar, height: 50, width: 50, crop: :fill, class: "dash-avatar" %>
          </div>
        <!-- Prénom / Nom -->
          <div class="d-flex flex-column results-info position-relative pb-1 ">
            <span class="results-name"><%= contact.first_name%> <%=contact.last_name.upcase %></span>
            <span class="result-company"><%=contact.company%></span>
            <%= link_to '', contact_path(contact), class:'stretched-link'  %>
          </div>
        <!-- Icons -->
        <div class="icon-dash">
          <div class="d-flex results-icons justify-content-center align-items-center pr-3">

            <%= link_to new_contact_note_path(contact) do  %>
            <div class="d-flex contact-dash-icon-green flex-column position-relative">
              <%= image_tag('writing-green.svg', class: 'card-image-writing') %>
              <i class="fas fa-plus alert-add green"></i>
            </div>
            <% end %>
            <%= link_to new_contact_alert_path(contact) do  %>
            <div class="d-flex contact-dash-icon-orange green flex-column justify-content-between position-relative">
              <%= image_tag('rappel.svg', class: 'card-image-writing') %>
              <i class="fas fa-plus alert-add" ></i>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <% else %>
    <p>Aucun contact ne correspond à votre recherche.</p>
  <% end %>
</div>

app/views/dashboards/_tagnotes.html.erb
    <% if notes && notes.empty? %>
    <div class="nonote">
      <p>Vous n'avez pas de note pour "<%= tag_labels.join('" ou "') %>".</p>
    </div>
    <% elsif notes && notes.any? %>
    <div class="d-flex flex-column results-tag-search-title">
      <span class=""> Notes associées pour : <span class="tags-search-results"><%= tag_labels.join(', ').capitalize %></span></span>
    </div>
      <% notes.each do |note| %>
          <div class="notes-search d-flex flex-column position-relative">

              <div class="notes-text-search d-flex flex-column">

                <div class="d-flex justify-content-between">
                  <span class="name-search"><%= note.contact.first_name %> <%= note.contact.last_name.upcase %></span>
                  <span class="notes-text-date-search"><%= I18n.l(note.updated_at, format: '%d %B %y') %></span>
                </div>

                <span class="notes-text-content-search"><%= note.content %></span>
              </div>

              <div class="tags-fiche-contact-results d-flex" data-note-id="<%= note.id %>" >
                    <% note.tags.each do |t| %>
                    <div class="tag-bis <%= t.color %>">
                      <span class="tag-text-note <%= tag.color %>" data-tag-id = "<%= t.id %>" ><%= t.label.capitalize %></span>
                    </div>
                  <% end %>
              </div>

              <%= link_to '', contact_path(note.contact), class:'stretched-link'  %>

          </div>
      <% end %> <!-- end each Intération notes associées aux tags-->
    <% end %> <!-- end condition de l'ensemble des notes non vides -->

app/views/dashboards/_tags.html.erb
<!--
<div class="form-check form-check-inline tag-form <%= tag.color %>" data-checkbox-id="<%= tag.id %>">
  <input hidden class="tag-bis" type="checkbox" value="<%= tag.id %>" name="note[tag_ids][]" id="note_tag_ids_<%=tag.id%>">
  <label  class="tag-text <%= tag.color %>" for="note_tag_ids_<%=tag.id%>"><%= tag.label.capitalize %></label>
</div>


 -->
 <div class="tags-search mt-2 flex-column" id="tag-search" >
  <span class="tag-header">Cliquer sur un tag pour l'ajouter</span>
  <div class = ''>
    <% tags.each do |tag| %>
      <div class="form-check form-check-inline tag-form tag-search-id <%= tag.color %>" data-checkbox-id="<%= tag.id %>">
        <input hidden class="tag-bis" type="number" value="<%= tag.id %>" name="search[tag_ids][]" id="search_tag_ids_<%=tag.id%>">
        <label  class="<%= tag.color %> tag-text" for="search_tag_ids_<%=tag.id%>"><%= tag.label.capitalize %></label>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/display.js.erb
function insertToNotes() {
  console.log('appel display')
  const tagsZone = document.getElementById('tag-search')
  tagsZone.style.display = "none";
  const notesList = document.getElementById('tag-notes-results')
  notesList.style.display= ""
  notesList.insertAdjacentHTML('beforeend', '<%= j render "tagnotes", params: @params, notes: @notes, search: @search %>')
}

insertToNotes()

app/views/dashboards/index.html.erb
<div class="dash-searchbar">
  <div class="search-bar d-flex justify-content-center mb-3">

    <%#= link_to dashboard_tag_path) do%>
      <p class="ml-3  dashboard-tag">TAG</p>
      <%# end %>

    <%= form_tag dashboard_results_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "placeholder-search search-name",
        placeholder: "Je cherche..."
      %>
    <% end %>
    <i class="fas fa-search mr-2 mt-2"></i>
  </div>
</div>

<div class="index-dash">
  <%if params[:query].present?  %>
    <% if @contacts.any?%>
      <ul class="list-group ml-3">
      <% @contacts.each do |contact| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="mt-0">
          <%= cl_image_tag contact.avatar, height: 50, width: 50, crop: :fill, class: "dash-avatar" %>
        </div>
        <div class="contact-name ml-2 text-left">
          <%= contact.first_name%> <%=contact.last_name%>
        </div>
        <!-- <div class=" ">
          <i class="fas fa-phone dash ml-3 mt-3"></i>
        </div> -->
        <div class="d-flex mr-3">
          <%= link_to new_contact_note_path(contact) do%>
          <div class="d-flex contact-dash-icon mr-3">
            <i class="fas fa-bell dash ml-3"></i>
            <i class="fas fa-plus dash"></i>
          </div>
          <% end %>
          <%= link_to new_contact_alert_path(contact) do%>
          <div class="d-flex contact-dash-icon ml-2">
            <i class="fas fa-sticky-note dash"></i>
            <i class="fas fa-plus dash" style="margin-left:3px;"></i>
          </div>
          <% end %>
        </div>
        </li>
        </div>
      <% end %>
      </ul>
    <% else %>
      <p>Aucun contact ne correspond à votre recherche.</p>
    <% end %>
  <% end %>
</div>

app/views/dashboards/search.html.erb
<!-- PARTIE BLEUE -->
<div class="d-flex justify-content-center navbar-dashboard">
  <div>
    <%= link_to dashboard_path do %>
      <%= image_tag('house-empty.svg', class: 'btn-home') %>
    <% end %>
  </div>
  <p class="dashboard-title">Easycontact</p>
  <%= link_to destroy_user_session_path, method: :delete do %>
           <%= image_tag('user.svg', class: 'btn-user') %>
     <% end %>
</div>

<!-- PARTIE ROSE -->

<div class="searchs-dashboard-tag">
  <div class="d-flex flex-column salutations-tag">
    <span class="dashboard-hey">Recherche par tags</span>
  </div>
  <div class="search-bar-tag">
    <%= simple_form_for :query, url: search_by_tags_path, remote: true,
      method: :get, html: { class: 'form-inline' } do |f| %>

      <!-- formulaire d'input hidden -->
      <div id="target"class="d-flex">
        <%= f.hidden_field :label, class: "placeholder-search", placeholder: "Tags",
         input_html: {value: ""}, label: false  %>

      </div>
      <!-- <div class="tag-dashboard d-flex justify-content-center align-items-center"> -->
         <span class="tag-dashboard-new-search d-flex justify-content-center align-items-center" id = "tagResetDiv">Nouvelle recherche</span>
        <%= f.button :submit, 'Go', class: 'tag-dashboard-tag d-flex justify-content-center align-items-center mt-0' %>
      <!-- </div> -->
    <% end %>
  </div>
</div>

<!-- PARTIE GRISE -->

<div class="tags-display-dashboard">
<!--  zone des tags qui nourrissent l'input si sélectionnés -->
  <br>
  <div id='query-tags'>
    <%= render 'tags', tags: @tags %>
  </div>

<!-- submit des tags est ICI -->

<!-- Resultat de la recherche par tag -->

  <!-- classe scroll-results dans _search.scss -->
  <div class = "scroll-results" id = "tag-notes-results">
    <%= render 'tagnotes', notes: @notes  %>
  </div>

</div>


<!-- à conserver sur cette page -->
<script type="text/javascript">
    $(function(){
        $(document).on('click','input[type=text]',function(){ this.select(); });
    });
</script>

app/views/dashboards/search_by_name.js.erb
function insertContacts() {
  console.log('hello')
  const contactsZone = document.getElementById('display-contacts')
  contactsZone.innerHTML = ""
  contactsZone.insertAdjacentHTML('beforeend', '<%= j render "searchcontacts", contacts: @contacts %>')
}

insertContacts()

app/views/dashboards/search_by_tags.js.erb
function insertToNotes() {
  console.log('appel display')
  const tagsZone = document.getElementById('tag-search')
  tagsZone.style.display = "none";
  const notesList = document.getElementById('tag-notes-results')
  notesList.innerHTML = ""
  notesList.style.display= ""
  notesList.insertAdjacentHTML('beforeend', '<%= j render "tagnotes", notes: @notes, search: @search, tag_labels: @tag_labels %>')
}

insertToNotes()

app/views/dashboards/show.html.erb
<!-- PARTIE BLEUE -->
<%=render 'shared/navbar', user: current_user %>



<!-- PARTIE ROSE -->
<div class="dash-back-blue">

  <div class="searchs-dashboard d-flex justify-content-center align-items-center flex-column pb-5">

    <div class="d-flex flex-column salutations">
      <span class="dashboard-hey">Hey <%=current_user.first_name.capitalize%></span>
      <span class="dashboard-question">qui avez-vous vu aujourd'hui ?</span>
    </div>

    <div class="search-bar d-flex justify-content-between">

        <%= form_tag search_by_name_path, method: :get, remote: true do %>
          <%= text_field_tag :query,
            params[:query],
            class: "placeholder-search",
            placeholder: "Jean Dupont"
          %>

          <div class="loupe-dash-search">
            <%= submit_tag("", class: "btn btn-default search", :style => "width:30px;") %>
            <%= image_tag ("loupe.svg"), :class => "loupe" %>
          </div>

          <%= link_to tag_search_path do  %>
            <div class="tag-dashboard d-flex justify-content-center align-items-center">
              <span class="tag-click">TAG</span>
            </div>
          <% end %>
        <% end %>

    </div>

  </div>

</div>

<!-- PARTIE GRISE -->

<!-- Liste alerte -->

<div class="dash-back-pink">

    <%if params[:query].nil?  %>

  <div class="rappels-dashboard d-flex justify-content-center mb-3" id="display-contacts">

    <div class="rappels-dash mb-5 pb-5">
      <%  if @upcoming_contacts_alerts.any? %>
      <div class="rappel-title">
        <span class="rappel-title">Rappels à venir</span>
      </div>
        <% @upcoming_contacts_alerts.each do |alert| %>


          <div class="rappels dash d-flex">

              <div class="date-rappels-dash ">
                <span class="rappels-text-date-dash d-flex align-items-center justify-content-center">
                  <%= I18n.l(alert.datetime, format: "%e") %><br><%= I18n.l(alert.datetime, format: "%B") %></span>
              </div>

              <%= link_to contact_path(alert.contact), class:'' do %>
              <div class="rappels-text-content-dashboard d-flex flex-column ">
                <span class="dash-rappel-name"><%= alert.contact.first_name %> <%= alert.contact.last_name.upcase %></span>
                <span class="dash-rappel-title"><%= alert.title %></span>
              </div>
              <% end %>
            </div>

        <% end %>

      <% else %>
        <p>"Vous n'avez pas d'alerte à venir."</p>
      <% end %>
    </div>

  </div>

</div>

<!-- Resultats query -->

<div class="dash-back-pink-query" id="display-contacts">
  <%else %>
    <%= render 'searchcontacts', contacts: @contacts %>
  <% end %>
</div>

<!-- Bouton new contact -->


<div class="footer-contact-dash d-flex justify-content-around pb-5">
  <div class="position-relative">
    <i class="fas fa-plus"></i>
  </div>

  <div class="button-plus-footer minus ">
    <%= link_to new_contact_path do %>
        <div class="lg-btn d-flex align-items-center  justify-content-center home mb-3">
          <?xml version="1.0"?>
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 350 350" style="enable-background:new 0 0 350 350;" xml:space="preserve" width="20px" height="20px" class=""><g><g>
            <path d="M175,171.173c38.914,0,70.463-38.318,70.463-85.586C245.463,38.318,235.105,0,175,0s-70.465,38.318-70.465,85.587   C104.535,132.855,136.084,171.173,175,171.173z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            <path d="M41.909,301.853C41.897,298.971,41.885,301.041,41.909,301.853L41.909,301.853z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            <path d="M308.085,304.104C308.123,303.315,308.098,298.63,308.085,304.104L308.085,304.104z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            <path d="M307.935,298.397c-1.305-82.342-12.059-105.805-94.352-120.657c0,0-11.584,14.761-38.584,14.761   s-38.586-14.761-38.586-14.761c-81.395,14.69-92.803,37.805-94.303,117.982c-0.123,6.547-0.18,6.891-0.202,6.131   c0.005,1.424,0.011,4.058,0.011,8.651c0,0,19.592,39.496,133.08,39.496c113.486,0,133.08-39.496,133.08-39.496   c0-2.951,0.002-5.003,0.005-6.399C308.062,304.575,308.018,303.664,307.935,298.397z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
          </g></g> </svg>
        </div>
    <% end %>
  </div>
</div>



<!-- à conserver sur cette page -->
<script type="text/javascript">
    $(function(){
        $(document).on('click','input[type=text]',function(){ this.select(); });
    });
</script>

app/views/dashboards/test.html.erb
<!-- Liste alerte -->

<div class="dash-back-pink">

    <%if params[:query].nil?  %>

  <div class="rappels-dashboard d-flex justify-content-center mb-3">

    <div class="rappels-dash mb-5 pb-5">
      <%  if @upcoming_contacts_alerts.any? %>
      <div class="rappel-title">
        <span class="rappel-title">Rappels à venir</span>
      </div>
        <% @upcoming_contacts_alerts.each do |alert| %>


          <div class="rappels dash d-flex position-relative">

            <div class="rappels-text-dash d-flex">

              <div class="date-rappels-dash">
                <span class="rappels-text-date-dash d-flex align-items-center justify-content-center"><%= I18n.l(alert.datetime, format: "%e") %><br><%= I18n.l(alert.datetime, format: "%B") %></span>
              </div>
              <%= link_to '', contact_path(alert.contact), class:'stretched-link'  %>
              <div class="rappels-text-content-dashboard d-flex flex-column">
                <span class="dash-rappel-name"><%= alert.contact.first_name %> <%= alert.contact.last_name.upcase %></span>
                <span class="dash-rappel-title"><%= alert.title %></span>
              </div>

            </div>

          </div>
        <% end %>

      <% else %>
        <p>"Vous n'avez pas d'alerte à venir."</p>
      <% end %>
    </div>

  </div>

</div>

<!-- Resultats query -->

<div class="dash-back-pink-query" id="display-contacts">
  <% else %>
      <%= render 'searchcontacts', contacts: @contacts %>
    <% end %>
</div>

<!-- Bouton new contact -->


<div class="footer-contact-dash d-flex justify-content-around">
  <div class="position-relative">
    <i class="fas fa-plus"></i>
  </div>

  <div class="button-plus-footer minus">
    <%= link_to new_contact_path do %>
        <div class="lg-btn d-flex align-items-center flex-column justify-content-center home">
          <?xml version="1.0"?>
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 350 350" style="enable-background:new 0 0 350 350;" xml:space="preserve" width="20px" height="20px" class=""><g><g>
            <path d="M175,171.173c38.914,0,70.463-38.318,70.463-85.586C245.463,38.318,235.105,0,175,0s-70.465,38.318-70.465,85.587   C104.535,132.855,136.084,171.173,175,171.173z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            <path d="M41.909,301.853C41.897,298.971,41.885,301.041,41.909,301.853L41.909,301.853z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            <path d="M308.085,304.104C308.123,303.315,308.098,298.63,308.085,304.104L308.085,304.104z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
            <path d="M307.935,298.397c-1.305-82.342-12.059-105.805-94.352-120.657c0,0-11.584,14.761-38.584,14.761   s-38.586-14.761-38.586-14.761c-81.395,14.69-92.803,37.805-94.303,117.982c-0.123,6.547-0.18,6.891-0.202,6.131   c0.005,1.424,0.011,4.058,0.011,8.651c0,0,19.592,39.496,133.08,39.496c113.486,0,133.08-39.496,133.08-39.496   c0-2.951,0.002-5.003,0.005-6.399C308.062,304.575,308.018,303.664,307.935,298.397z" data-original="#000000" class="active-path" data-old_color="#000000" fill="#FFFFFF"/>
          </g></g> </svg>
        </div>
    <% end %>
  </div>
</div>



<!-- à conserver sur cette page -->
<script type="text/javascript">
    $(function(){
        $(document).on('click','input[type=text]',function(){ this.select(); });
    });
</script>